# Generated by Django 4.0 on 2021-12-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pollinations", "0002_processingqueue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingqueue",
            name="processed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
