# Generated by Django 4.0 on 2021-12-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollinations', '0003_alter_processingqueue_processed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingqueue',
            name='processing_started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
