# Generated by Django 4.0 on 2021-12-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pollinations", "0004_processingqueue_processing_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollinationscid",
            name="input_fps",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pollinationscid",
            name="input_height",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pollinationscid",
            name="input_iterations",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pollinationscid",
            name="input_notebook_ipynb",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pollinationscid",
            name="input_resolution",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pollinationscid",
            name="input_social",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pollinationscid",
            name="input_style",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pollinationscid",
            name="input_super_resolution",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pollinationscid",
            name="input_width",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pollinationscid",
            name="output_done",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pollinationscid",
            name="output_gpu",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pollinationscid",
            name="output_gpu_memory",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pollinationscid",
            name="output_log",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pollinationscid",
            name="output_run_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pollinationscid",
            name="output_status",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pollinationscid",
            name="output_success",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pollinationscid",
            name="step_size",
            field=models.TextField(null=True),
        ),
    ]
