# Generated by Django 4.0 on 2021-12-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollinations', '0009_rename_step_size_content_input_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.JSONField(null=True),
        ),
    ]
