# Generated by Django 4.0 on 2021-12-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pollinations", "0010_alter_content_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="input_fix_camera",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="input_image_prompt_file",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="input_images_prompt_weight",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="input_input_text_prompt_weight",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="input_learning_rate",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="input_seed",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="input_steps",
            field=models.TextField(null=True),
        ),
    ]
