# Generated by Django 4.0 on 2021-12-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pollinations", "0014_content_input_model_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="input_batch_size",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="input_prompt",
            field=models.TextField(null=True),
        ),
    ]
