# Generated by Django 4.0 on 2021-12-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pollinations", "0016_content_input_all_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="input_model",
            field=models.TextField(null=True),
        ),
    ]
