# Generated by Django 4.0 on 2021-12-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pollinations", "0017_content_input_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="input_youtube_dl_link",
            field=models.TextField(null=True),
        ),
    ]
