# Generated by Django 4.0 on 2021-12-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollinations', '0018_content_input_youtube_dl_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='input_upscale_factor',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='input_video_file',
            field=models.TextField(null=True),
        ),
    ]
