# Generated by Django 4.0 on 2021-12-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollinations', '0019_content_input_upscale_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='input_diffusion_model',
            field=models.TextField(null=True),
        ),
    ]
