# Generated by Django 4.0 on 2021-12-28 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pollinations", "0024_content_input_file_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="input_trebles_story_spee",
            new_name="input_trebles_story_speed",
        ),
    ]
