# Generated by Django 4.0 on 2021-12-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pollinations",
            "0025_rename_input_trebles_story_spee_content_input_trebles_story_speed",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="input_frame_rate",
            field=models.TextField(null=True),
        ),
    ]
