# Generated by Django 4.0 on 2021-12-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pollinations", "0026_content_input_frame_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="input_imagemodel",
            field=models.TextField(null=True),
        ),
    ]
