# Generated by Django 4.0 on 2021-12-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pollinations", "0027_content_input_imagemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="input_image_model",
            field=models.TextField(null=True),
        ),
    ]
