# Generated by Django 4.0 on 2021-12-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pollinations", "0028_content_input_image_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="input_colorize",
            field=models.TextField(null=True),
        ),
    ]
