# Generated by Django 4.0 on 2021-12-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollinations', '0029_content_input_colorize'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='input_city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='input_country',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='input_doctolib_email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='input_doctolib_password',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='input_dose',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='input_start_date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='input_twofa_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='input_vaccine',
            field=models.TextField(null=True),
        ),
    ]
