# Generated by Django 4.0 on 2021-12-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollinations', '0031_content_input_prompts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='raw_text_input',
            new_name='text_input',
        ),
    ]
