# Generated by Django 4.0 on 2021-12-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollinations', '0032_rename_raw_text_input_content_text_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='notebook_hash',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
